apiVersion: v1
kind: Service
metadata:
  name: training-api
  labels:
    app: training-api
spec:
  type: LoadBalancer
  selector:
    app: training-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
