apiVersion: v1
kind: Service
metadata:
  name: meta-trainer
spec:
  selector:
    app: meta-trainer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: LoadBalancer
