apiVersion: v1
kind: Service
metadata:
  name: hf-unsloth-trainer
spec:
  selector:
    app: hf-unsloth-trainer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
